# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike_2\Eclipse workspace\Betty\src\GUI\Betty_MainWindow.ui'
#
# Created: Sun Mar 28 17:23:34 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Betty_MainWindow(object):
    def setupUi(self, Betty_MainWindow):
        Betty_MainWindow.setObjectName("Betty_MainWindow")
        Betty_MainWindow.resize(802, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Betty_MainWindow.sizePolicy().hasHeightForWidth())
        Betty_MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Horse"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Betty_MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Betty_MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.raceTable = QtGui.QTableView(self.centralwidget)
        self.raceTable.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.raceTable.setProperty("showDropIndicator", False)
        self.raceTable.setDragDropOverwriteMode(False)
        self.raceTable.setAlternatingRowColors(True)
        self.raceTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.raceTable.setShowGrid(False)
        self.raceTable.setGridStyle(QtCore.Qt.NoPen)
        self.raceTable.setObjectName("raceTable")
        self.raceTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.raceTable)
        Betty_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Betty_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Betty_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Betty_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Betty_MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Betty_MainWindow)
        self.toolBar.setObjectName("toolBar")
        Betty_MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.raceDockWidget = QtGui.QDockWidget(Betty_MainWindow)
        self.raceDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.raceDockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.raceDockWidget.setObjectName("raceDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameEdit = QtGui.QLineEdit(self.frame)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.courseCombo = QtGui.QComboBox(self.frame)
        self.courseCombo.setEditable(True)
        self.courseCombo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.courseCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.courseCombo.setObjectName("courseCombo")
        self.courseCombo.addItem("")
        self.courseCombo.addItem("")
        self.courseCombo.addItem("")
        self.courseCombo.addItem("")
        self.courseCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.courseCombo)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.timeEdit = QtGui.QTimeEdit(self.frame)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.milesSpinner = QtGui.QSpinBox(self.frame)
        self.milesSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.milesSpinner.setReadOnly(False)
        self.milesSpinner.setObjectName("milesSpinner")
        self.horizontalLayout.addWidget(self.milesSpinner)
        self.furlongCombo = QtGui.QComboBox(self.frame)
        self.furlongCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.furlongCombo.setObjectName("furlongCombo")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.furlongCombo.addItem("")
        self.horizontalLayout.addWidget(self.furlongCombo)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.classCombo = QtGui.QComboBox(self.frame)
        self.classCombo.setEditable(True)
        self.classCombo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.classCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.classCombo.setObjectName("classCombo")
        self.classCombo.addItem("")
        self.classCombo.addItem("")
        self.classCombo.addItem("")
        self.classCombo.addItem("")
        self.horizontalLayout.addWidget(self.classCombo)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.prizeSpinner = QtGui.QSpinBox(self.frame)
        self.prizeSpinner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prizeSpinner.setMaximum(10000000)
        self.prizeSpinner.setSingleStep(1000)
        self.prizeSpinner.setObjectName("prizeSpinner")
        self.horizontalLayout.addWidget(self.prizeSpinner)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.frame)
        self.raceDockWidget.setWidget(self.dockWidgetContents)
        Betty_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.raceDockWidget)
        self.dockWidget = QtGui.QDockWidget(Betty_MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.oddsGroupBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.oddsGroupBox.setObjectName("oddsGroupBox")
        self.oddsLayout = QtGui.QVBoxLayout(self.oddsGroupBox)
        self.oddsLayout.setObjectName("oddsLayout")
        self.verticalLayout_6.addWidget(self.oddsGroupBox)
        self.sortBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.sortBox.setObjectName("sortBox")
        self.sortLayout = QtGui.QVBoxLayout(self.sortBox)
        self.sortLayout.setObjectName("sortLayout")
        self.verticalLayout_6.addWidget(self.sortBox)
        self.dataGroupBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.dataGroupBox.setObjectName("dataGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dataGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.editRoundsButton = QtGui.QPushButton(self.dataGroupBox)
        self.editRoundsButton.setObjectName("editRoundsButton")
        self.verticalLayout_3.addWidget(self.editRoundsButton)
        self.editAdjustsButton = QtGui.QPushButton(self.dataGroupBox)
        self.editAdjustsButton.setEnabled(True)
        self.editAdjustsButton.setObjectName("editAdjustsButton")
        self.verticalLayout_3.addWidget(self.editAdjustsButton)
        self.verticalLayout_6.addWidget(self.dataGroupBox)
        self.horseGroupBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.horseGroupBox.setObjectName("horseGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.horseGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.addButton = QtGui.QPushButton(self.horseGroupBox)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_7.addWidget(self.addButton)
        self.deleteButton = QtGui.QPushButton(self.horseGroupBox)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_7.addWidget(self.deleteButton)
        self.verticalLayout_6.addWidget(self.horseGroupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        Betty_MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionNew = QtGui.QAction(Betty_MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/New"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(Betty_MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(Betty_MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionDownload = QtGui.QAction(Betty_MainWindow)
        self.actionDownload.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Web"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDownload.setIcon(icon4)
        self.actionDownload.setObjectName("actionDownload")
        self.actionQuit = QtGui.QAction(Betty_MainWindow)
        self.actionQuit.setCheckable(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Quit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRecent_Files = QtGui.QAction(Betty_MainWindow)
        self.actionRecent_Files.setObjectName("actionRecent_Files")
        self.actionSave_As = QtGui.QAction(Betty_MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Save As"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon6)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtGui.QAction(Betty_MainWindow)
        self.actionPrint.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Print"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setObjectName("actionPrint")
        self.actionAbout = QtGui.QAction(Betty_MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent_Files)
        self.menuFile.addAction(self.actionDownload)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDownload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.label.setBuddy(self.nameEdit)
        self.label_2.setBuddy(self.courseCombo)
        self.label_3.setBuddy(self.dateEdit)
        self.label_4.setBuddy(self.timeEdit)
        self.label_5.setBuddy(self.classCombo)
        self.label_8.setBuddy(self.prizeSpinner)

        self.retranslateUi(Betty_MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), Betty_MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(Betty_MainWindow)
        Betty_MainWindow.setTabOrder(self.nameEdit, self.courseCombo)
        Betty_MainWindow.setTabOrder(self.courseCombo, self.dateEdit)
        Betty_MainWindow.setTabOrder(self.dateEdit, self.timeEdit)
        Betty_MainWindow.setTabOrder(self.timeEdit, self.milesSpinner)
        Betty_MainWindow.setTabOrder(self.milesSpinner, self.furlongCombo)
        Betty_MainWindow.setTabOrder(self.furlongCombo, self.classCombo)
        Betty_MainWindow.setTabOrder(self.classCombo, self.prizeSpinner)
        Betty_MainWindow.setTabOrder(self.prizeSpinner, self.editRoundsButton)
        Betty_MainWindow.setTabOrder(self.editRoundsButton, self.editAdjustsButton)
        Betty_MainWindow.setTabOrder(self.editAdjustsButton, self.raceTable)

    def retranslateUi(self, Betty_MainWindow):
        Betty_MainWindow.setWindowTitle(QtGui.QApplication.translate("Betty_MainWindow", "Betty", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Betty_MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.raceDockWidget.setWindowTitle(QtGui.QApplication.translate("Betty_MainWindow", "Race Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Betty_MainWindow", "Race &Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Betty_MainWindow", "Race &Course", None, QtGui.QApplication.UnicodeUTF8))
        self.courseCombo.setItemText(0, QtGui.QApplication.translate("Betty_MainWindow", "Ascot", None, QtGui.QApplication.UnicodeUTF8))
        self.courseCombo.setItemText(1, QtGui.QApplication.translate("Betty_MainWindow", "Aintree", None, QtGui.QApplication.UnicodeUTF8))
        self.courseCombo.setItemText(2, QtGui.QApplication.translate("Betty_MainWindow", "Cheltenham", None, QtGui.QApplication.UnicodeUTF8))
        self.courseCombo.setItemText(3, QtGui.QApplication.translate("Betty_MainWindow", "Kempton", None, QtGui.QApplication.UnicodeUTF8))
        self.courseCombo.setItemText(4, QtGui.QApplication.translate("Betty_MainWindow", "Newmarket", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Betty_MainWindow", "&Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Betty_MainWindow", "&Time", None, QtGui.QApplication.UnicodeUTF8))
        self.timeEdit.setDisplayFormat(QtGui.QApplication.translate("Betty_MainWindow", "HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Betty_MainWindow", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.milesSpinner.setSuffix(QtGui.QApplication.translate("Betty_MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(0, QtGui.QApplication.translate("Betty_MainWindow", "0f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(1, QtGui.QApplication.translate("Betty_MainWindow", "1f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(2, QtGui.QApplication.translate("Betty_MainWindow", "2f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(3, QtGui.QApplication.translate("Betty_MainWindow", "3f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(4, QtGui.QApplication.translate("Betty_MainWindow", "4f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(5, QtGui.QApplication.translate("Betty_MainWindow", "5f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(6, QtGui.QApplication.translate("Betty_MainWindow", "6f", None, QtGui.QApplication.UnicodeUTF8))
        self.furlongCombo.setItemText(7, QtGui.QApplication.translate("Betty_MainWindow", "7f", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Betty_MainWindow", "Race C&lass", None, QtGui.QApplication.UnicodeUTF8))
        self.classCombo.setItemText(0, QtGui.QApplication.translate("Betty_MainWindow", "Class A", None, QtGui.QApplication.UnicodeUTF8))
        self.classCombo.setItemText(1, QtGui.QApplication.translate("Betty_MainWindow", "Class B", None, QtGui.QApplication.UnicodeUTF8))
        self.classCombo.setItemText(2, QtGui.QApplication.translate("Betty_MainWindow", "Class C", None, QtGui.QApplication.UnicodeUTF8))
        self.classCombo.setItemText(3, QtGui.QApplication.translate("Betty_MainWindow", "Class D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Betty_MainWindow", "Prize Money", None, QtGui.QApplication.UnicodeUTF8))
        self.prizeSpinner.setPrefix(QtGui.QApplication.translate("Betty_MainWindow", "£", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("Betty_MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.oddsGroupBox.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "&Odds", None, QtGui.QApplication.UnicodeUTF8))
        self.sortBox.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "Sort Order", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGroupBox.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "Data Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.editRoundsButton.setText(QtGui.QApplication.translate("Betty_MainWindow", "Edit Rounds", None, QtGui.QApplication.UnicodeUTF8))
        self.editAdjustsButton.setText(QtGui.QApplication.translate("Betty_MainWindow", "Edit Adjustments", None, QtGui.QApplication.UnicodeUTF8))
        self.horseGroupBox.setTitle(QtGui.QApplication.translate("Betty_MainWindow", "Horse Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("Betty_MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("Betty_MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("Betty_MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Create a new race", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Betty_MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Open a race file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Betty_MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Save this race", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload.setText(QtGui.QApplication.translate("Betty_MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Download race information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDownload.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Betty_MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Quit Betty", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Files.setText(QtGui.QApplication.translate("Betty_MainWindow", "Recent Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("Betty_MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Save this race in a new file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("Betty_MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setToolTip(QtGui.QApplication.translate("Betty_MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "Print this race", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("Betty_MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("Betty_MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("Betty_MainWindow", "About Betty", None, QtGui.QApplication.UnicodeUTF8))

import Betty_rc
